steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['gcloud', 'functions', 'deploy', 'testbuildescalate', '--region=europe-west1', '--source=.', '--trigger-http', '--runtime=python313']
