steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - gcloud
      - functions
      - deploy
      - escalation_notify
      - '--region=europe-west1'
      - '--source=function/.'
      - '--trigger-http'
      - '--runtime=python313'
options:
  logging: CLOUD_LOGGING_ONLY
